apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-and-deploy
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: ui-repo
      resourceRef:
        name: ui-repo
    - name: ui-image
      resourceRef:
        name: ui-image
